### ISSUE TITLE
Can't access web-api from localhost.

### ISSUE THREAD

**Issue by anantDabhi1** [Knawat/interviews-challenges#11]
Can't access web-api from localhost.

When I call web-api from localhost it throws an error that 
**"Access to fetch at 'https://dev.mp.knawat.io/api/token' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status."** 

![image](https://user-images.githubusercontent.com/34566545/74631348-befbe900-5182-11ea-8914-d226f0592751.png)

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by ElGreetly** [comment]
Issue fixed for `localhost` requests
